import {unzipSync,strFromU8} from 'fflate';
import {chunkPages,detectTitle} from './rag.js';
import {assessOcr,waitForOcr} from './ocr-quality.js';
export const UPLOAD_ACCEPT='.pdf,.docx,.xls,.xlsx,.ppt,.pptx,.jpg,.jpeg,.png,.gif,.giff,.webp,.bmp,.xml,.txt,.md,.csv,.tsv,.json';
const images=new Set(['jpg','jpeg','png','gif','giff','webp','bmp']);
export function validateUpload(file){const ext=file.name.split('.').pop().toLowerCase();if(ext==='doc')throw Error('Legacy DOC needs conversion. Save it as DOCX or PDF, then upload.');if(!UPLOAD_ACCEPT.split(',').includes('.'+ext))throw Error('Unsupported format. Use PDF, DOCX, XLS/XLSX, PPT/PPTX, images, XML, text, CSV or JSON.');if(file.size>20*1024*1024)throw Error('Upload a file smaller than 20 MB.');return ext;}
export function safeXml(text){if(/<!DOCTYPE|<!ENTITY/i.test(text))throw Error('XML document types and entities are not supported.');const xml=new DOMParser().parseFromString(text,'application/xml');if(xml.getElementsByTagName('parsererror').length)throw Error('Invalid XML document.');return xml;}
const nodes=(xml,local)=>Array.from(xml.getElementsByTagNameNS('*',local));
function officeText(text){return nodes(safeXml(text),'p').map(p=>nodes(p,'t').map(n=>n.textContent).join('')).filter(Boolean).join('\n');}
function archive(bytes){let total=0;return unzipSync(bytes,{filter:f=>{total+=f.originalSize;if(total>40*1024*1024||f.originalSize>10*1024*1024)throw Error('Office archive exceeds decompression limits.');return /^(word\/document\.xml|ppt\/slides\/slide\d+\.xml|ppt\/presentation\.xml|ppt\/_rels\/presentation\.xml\.rels)$/.test(f.name);}});}
export function legacySlides(bytes,CFB){const stream=CFB.find(CFB.read(bytes,{type:'array'}),'PowerPoint Document');if(!stream?.content)throw Error('Not a readable legacy PowerPoint file. Save as PPTX.');const b=new Uint8Array(stream.content),v=new DataView(b.buffer,b.byteOffset,b.byteLength),slides=[];let records=0;function walk(start,end,slide,depth=0){if(depth>32)throw Error('PowerPoint nesting limit exceeded.');for(let p=start;p+8<=end;){if(++records>200000)throw Error('PowerPoint record limit exceeded.');const flags=v.getUint16(p,true),type=v.getUint16(p+2,true),next=p+8+v.getUint32(p+4,true);if(next>end||next<=p)throw Error('Damaged PowerPoint record.');let active=slide;if(type===1006){active=[];slides.push(active);}if((flags&15)===15)walk(p+8,next,active,depth+1);else if(active&&(type===4000||type===4008))active.push(new TextDecoder(type===4000?'utf-16le':'windows-1252').decode(b.subarray(p+8,next)).replace(/\r/g,'\n'));p=next;}}walk(0,b.length,null);if(!slides.length)throw Error('No readable slides found. Save as PPTX or PDF.');return slides.map((s,i)=>({page:i+1,text:s.join('\n'),sourceLabel:`Slide ${i+1} (legacy storage order)`}));}
function finish(file,pages,format,warnings,ocr,processing){if(pages.length>200)throw Error('Maximum 200 source sections, sheets or slides.');if(pages.reduce((s,p)=>s+p.text.length,0)>2000000)throw Error('Extracted text exceeds 2 million characters. Upload a smaller file.');const t=performance.now();pages=pages.map(p=>({...p,title:p.title||detectTitle(p.text,p.page),origin:p.origin||'document-text'}));const structureMs=performance.now()-t,start=performance.now(),chunks=chunkPages(pages),chunkingMs=performance.now()-start;const labels=new Map(pages.map(p=>[p.page,p.sourceLabel]));chunks.forEach(c=>c.sourceLabel=labels.get(c.page));if(!chunks.length)warnings.push('No readable text was found. Check scan quality; diagrams require manual review.');return {name:file.name,format,pages,chunks,warnings,ocr,pageReport:pages.map(p=>({page:p.page,sourceLabel:p.sourceLabel,status:p.text?(p.origin==='ocr'?'ocr':'text'):'unknown',short:p.text.length<40})),processing:{...processing,structureMs,chunkMs:chunkingMs,indexMs:0},chunkingMs,sourceLookup:new Map(chunks.map(c=>[c.id,c]))};}
export async function readDocument(file,onProgress,options={}){const start=performance.now(),ext=validateUpload(file);const check=()=>{if(options.signal?.aborted)throw new DOMException('Document processing cancelled.','AbortError');};check();if(ext==='pdf'){const {readPdf}=await import('./pdf.js');return {...await readPdf(file,onProgress,options),format:'pdf'};}const validateMs=performance.now()-start,decodeStart=performance.now();let pages=[],warnings=[],ocr={enabled:!!options.ocrEnabled,language:options.ocrLanguage||'English',attempted:0,recognized:0,failed:0},ocrMs=0;options.onStatus?.(`Reading ${ext.toUpperCase()} document…`);
if(images.has(ext)){if(!options.ocrEnabled)throw Error('Enable local OCR to read images.');if(['gif','giff'].includes(ext))warnings.push('GIF: only the first frame is indexed.');const url=URL.createObjectURL(file),image=new Image();let session,canvas;try{await waitForOcr(new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=()=>reject(Error('Image cannot be decoded.'));image.src=url;}),{signal:options.signal,timeoutMs:15000});check();if(image.naturalWidth*image.naturalHeight>40000000)throw Error('Resize images larger than 40 megapixels.');canvas=document.createElement('canvas');const scale=Math.min(1,2400/Math.max(image.naturalWidth,image.naturalHeight));canvas.width=Math.ceil(image.naturalWidth*scale);canvas.height=Math.ceil(image.naturalHeight*scale);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);const {createOcrSession}=await import('./ocr.js');session=createOcrSession({language:ocr.language,signal:options.signal,onProgress:options.onStatus});ocr.attempted=1;const t=performance.now(),result=assessOcr(await session.recognize(canvas,1));ocrMs=performance.now()-t;check();if(result.accepted){ocr.recognized=1;pages=[{page:1,text:result.text,sourceLabel:'Image 1',origin:'ocr',ocrConfidence:result.confidence}];}else{ocr.failed=1;warnings.push(result.reason);pages=[{page:1,text:'',sourceLabel:'Image 1'}];}}finally{session?.close();image.onload=null;image.onerror=null;image.src='';URL.revokeObjectURL(url);if(canvas){canvas.width=0;canvas.height=0;}}}
else{const bytes=new Uint8Array(await file.arrayBuffer());check();if(ext==='docx'||ext==='pptx'){const files=archive(bytes);if(ext==='docx'){if(!files['word/document.xml'])throw Error('Not a readable DOCX file.');pages=[{page:1,text:officeText(strFromU8(files['word/document.xml'])),sourceLabel:'Word document (paragraph order)'}];}else{if(!files['ppt/presentation.xml']||!files['ppt/_rels/presentation.xml.rels'])throw Error('Presentation slide order is missing.');const map=new Map(nodes(safeXml(strFromU8(files['ppt/_rels/presentation.xml.rels'])),'Relationship').map(r=>[r.getAttribute('Id'),r.getAttribute('Target')]));pages=nodes(safeXml(strFromU8(files['ppt/presentation.xml'])),'sldId').map((s,i)=>{const target=map.get(s.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id')),path=target?.startsWith('/')?target.slice(1):`ppt/${target}`;if(!files[path])throw Error('A referenced slide is missing.');return {page:i+1,text:officeText(strFromU8(files[path])),sourceLabel:`Slide ${i+1}`};});}warnings.push('Office text only: embedded images, speaker notes, drawing equations and visual layout are not interpreted.');}
else if(['xls','xlsx','csv','tsv','ppt'].includes(ext)){const XLSX=await import('xlsx');if(ext==='ppt'){pages=legacySlides(bytes,XLSX.CFB);warnings.push('Legacy PPT references use storage order, which may differ from slideshow order. Save as PPTX for exact order.');}else{if(ext==='xlsx')archive(bytes);const book=XLSX.read(bytes,{type:'array',cellFormula:false,cellHTML:false});if(book.SheetNames.length>200)throw Error('Maximum 200 sheets.');pages=book.SheetNames.map((name,i)=>{const sheet=book.Sheets[name];if(sheet['!ref']){const r=XLSX.utils.decode_range(sheet['!ref']);if((r.e.r-r.s.r+1)*(r.e.c-r.s.c+1)>100000)throw Error('A sheet exceeds 100,000 cells.');}return {page:i+1,title:name,sourceLabel:`Sheet: ${name}`,text:XLSX.utils.sheet_to_json(sheet,{header:1,raw:false,blankrows:false}).map(row=>row.join(' | ')).join('\n')};});warnings.push('Sheets are read as rows. Stored formula values only; macros are never executed. Charts and images are not interpreted.');}}
else{let text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);if(ext==='xml'){const xml=safeXml(text);text=Array.from(xml.getElementsByTagName('*')).filter(e=>!e.children.length&&e.textContent.trim()).map(e=>`${e.localName}: ${e.textContent.trim()}`).join('\n');}if(ext==='json')JSON.parse(text);pages=[{page:1,text,sourceLabel:`${ext.toUpperCase()} document`}];}}
check();onProgress?.(pages.length,pages.length);return finish(file,pages,images.has(ext)?'image':ext,warnings,ocr,{validateMs,decodeMs:performance.now()-decodeStart-ocrMs,ocrMs});}
