const step=(id,title,tool,purpose,input,output,validation,detail,extra={})=>({id,title,tool,purpose,input,output,validation,detail,...extra});
const measured=ms=>ms==null?'Not measured':ms<1000?`${Math.round(ms)} ms`:`${(ms/1000).toFixed(2)} s`;
export function buildFlowPaths({doc,vectors,trace,mode='extractive',aiConfigured=false,studyTool='Study material'}={}){
 const timing=doc?.processing||{},ocr=doc?.ocr;
 const composition=mode==='ai'?(aiConfigured?'Groq LLM · optional cloud':'Groq LLM · setup required'):mode==='local'?'Source selection + local NLLB':'Source selection · no LLM call';
 return {
 upload:{title:'Prepare a document',summary:'Readable text becomes reusable passages with source references. Optional stages depend on the file and your settings.',steps:[
 step('validate','Check the file','Local upload validator','Reject unsupported files and oversized inputs before reading.','Selected file','Accepted format and size','20 MB limit; format-specific extraction limits.','Legacy DOC needs DOCX/PDF conversion. Unsupported files leave the previous document available.',{metric:measured(timing.validateMs)}),
 step('decode','Read the content','PDF.js / fflate / SheetJS / DOMParser','Use the appropriate reader for your file.','PDF, DOCX, PPT/PPTX, XLS/XLSX, XML or text','Text in original source order','Check PDF signatures, Office archive bounds, XML syntax and sheet limits.','PDF preserves page numbers; PPTX follows slide relationships; sheets retain their names. Word references use paragraph order.',{metric:measured(timing.decodeMs)}),
 step('ocr','Recognize printed scans','Tesseract.js · browser WASM','Read printed image text when a text layer is missing.','Image or image-only PDF page','Recognized text + OCR provenance','Blank PDF pages skip OCR; empty/noisy/low-scoring recognition is excluded.','English, Tamil and Hindi printed text are supported. First use downloads public models; images stay local. GIF reads its first frame. Diagrams and handwriting need manual review.',{optional:true,status:ocr?(!ocr.enabled?'Disabled':ocr.attempted?`${ocr.recognized}/${ocr.attempted} recognized`:'Skipped for this file'):'Available when needed',metric:ocr?.attempted?measured(timing.ocrMs):'Not used'}),
 step('structure','Keep source identity','Heuristic headings + source metadata','Attach a readable topic and its original location.','Extracted text','Headings, pages/slides/sheets and OCR origin','Unreadable content stays visible in coverage; it is not invented.','A source ID identifies evidence. A location label explains where to verify it in the original file.',{metric:measured(timing.structureMs)}),
 step('chunk','Make small passages','Page-aware overlapping chunker','Keep retrieval context manageable without dropping the end of a source.','Readable source text','Passages S1, S2, S3…','Chunks preserve source boundaries and original location metadata.','Default chunks contain 150 words with 25-word overlap. Image transcriptions must be reviewed before indexing. Whole-document study tools consider every readable chunk.',{metric:doc?`${doc.chunks.length} passages · ${measured(timing.chunkMs)}`:'Waiting for a document'}),
 step('embed','Add meaning-based search','Optional multilingual E5 · browser WASM','Represent passage meanings as vectors for semantic retrieval.','Passage text','Normalized passage vectors','Use passage/query prefixes and combine ranks with keyword search.','Enable semantic search in Ask this document. Upload alone does not create vectors. Initial model download and inference depend on your device.',{optional:true,status:vectors?'Enabled':'Not enabled',metric:vectors?`${vectors.length} vectors`:'No embedding call'}),
 step('index','Reuse the session index','Browser session memory','Keep passages available for later study tools and questions.','Passages + optional vectors','Reusable source lookup','Replacing/removing a document clears its session data.','The deployed app uses session memory. Qdrant persistence and reranking are future improvements, not active tools.',{metric:doc?.needsReview?'Awaiting image transcription approval':doc?`${doc.chunks.length} indexed passages`:'Waiting for a document'})]},
 question:{title:'Answer a question',summary:'Retrieve relevant evidence, construct a response in the selected mode, then expose supporting sources.',steps:[
 step('question','Ask a focused question','Student question form','Make the information need explicit.','Question + answer language','Search request','Question length is bounded.','A specific topic or comparison usually produces more useful evidence than a very broad question.'),
 step('translate','Prepare search terms','Optional NLLB / protected AI query translation','Translate non-English questions for the current English-search workflow.','Tamil/Hindi question when translation is selected','Search terms for retrieval','Retain the original question and language preference.','Translation can be imperfect. Multilingual semantic retrieval is optional; cross-language quality is not guaranteed.',{optional:true,status:mode==='extractive'?'Source language search':mode==='local'?'Local translation selected':'AI translation requires setup'}),
 step('retrieve','Find relevant passages',vectors?'BM25 + E5 rank fusion':'BM25 keyword retrieval','Rank evidence relevant to the question.','Search terms + session passages','Up to five candidate passages','Lexical/rank scores are ordering signals, not factual confidence.','BM25 ranks keyword matches. With semantic search enabled, vector and keyword ranks are combined; identical passages are removed.',{metric:trace?.kind==='Question answering'?`${trace.evidence.length} selected passages`:'Uses the current session index'}),
 step('context','Build the evidence context','Bounded source passages','Give the response builder a traceable evidence set.','Retrieved passage text and source IDs','Relevant context with locations','Unrelated or missing evidence must not become an invented answer.','Ask uses retrieved evidence. Mind maps, roadmaps and notes use whole-document coverage instead of only the question’s top five results.'),
 step('compose','Create the response',composition,'Use the selected mode to produce a useful response.','Question + evidence','Source statements, translated statements or an AI explanation','AI mode needs a server key and workspace token; source mode works locally.','Source mode selects document statements. Local mode translates source-based content on-device. Configured AI mode sends selected extracted evidence through Vercel to Groq.',{status:mode==='ai'?(aiConfigured?'Cloud AI configured':'Cloud AI not configured'):mode==='local'?'Local translation mode':'Source mode'}),
 step('cite','Show and verify sources','Source links + output validation','Let students check an answer against its evidence.','Response + source IDs','Answer with clickable source references','AI schemas validate known IDs, quote matches and MCQ structure.','A valid source ID does not prove an explanation is correct. Review the cited text and original scan, especially OCR formulas and units.',{metric:trace?.evidence?.length?`${trace.evidence.length} evidence passages in last trace`:'Open source buttons to verify'})]},
 materials:{title:'Create source-linked study materials',summary:'Mind maps, roadmaps, notes and other whole-document tools cover all readable passages. They do not use only a question’s top-five retrieval results.',steps:[
 step('choose','Choose a study tool','Student study dashboard','Select the output that fits the learning task.','Current document + class/subject/language','Requested study tool','A document with readable passages is required.','Mind maps organize topic relationships; roadmaps organize learning order; notes and cards support revision.',{status:studyTool}),
 step('coverage','Cover readable sources','Whole-document section batches','Include evidence across the readable document.','All indexed passages','Bounded topic/section evidence','Unreadable pages and unsupported embedded content are excluded visibly.','AI tools process bounded evidence batches. Source tools consider all readable chunks; this differs from question answering’s top-K retrieval.',{metric:doc?`${doc.chunks.length} passages considered`:'Waiting for a document'}),
 step('essential','Select essential ideas','Source fact selection / teaching prompts','Keep the output focused on useful concepts and relationships.','Topic evidence','Key concepts, formulas and relevant facts','Remove repeated facts and retain conditions, units and source IDs.','Source graphs select up to three essential facts per topic. AI graph schemas require concise named subtopics; output still needs teacher/student review.'),
 step('material','Build structured content',composition,'Create the selected study format with evidence links.','Section evidence + study-tool request','Structured notes, graph topics, cards or practice items','AI output checks nested sources, exact quoted text and four-option MCQs.','Source mode organizes document statements. AI mode can explain evidence when configured. Practice questions are generated exercises, not official exam predictions.'),
 step('language','Apply the output language','Optional local NLLB / AI language instruction','Support the requested language while retaining source references.','Structured content + language preference','Source-language, locally translated or AI-language items','Keep original quotations, formulas and source IDs available.','Local mode uses on-device translation and may need a large first download. Configured AI mode generates in the requested language. Review translation accuracy.',{optional:true,status:mode==='local'?'Local translation selected':mode==='ai'?'AI language instruction':'Document language preserved'}),
 step('render','Render and inspect','SVG graphs / professional notes / cards / quizzes','Present material in a readable visual format.','Structured study items','Interactive learning output + source controls','Keep selected-topic essentials focused; verify cited evidence.','Mind maps and roadmaps use professional fonts and graphical layouts. Source buttons open the original reference; SVG/print exports support revision.') ]},
 development:{title:'How MCP and development tools help',summary:'This is the project-development workflow. MCP is used by the coding agent; student uploads and questions do not call GitHub MCP.',steps:[
 step('requirements','Define the change','Student feedback + coding agent','Turn a request into reviewable behavior.','Problem and desired outcome','Requirements and acceptance checks','Identify scope, local/cloud boundaries and unsupported behavior.','For example, a scanned page needs OCR; it does not automatically need an LLM or diagram interpretation.'),
 step('skill','Apply the review skill','rag-quality-review skill','Reuse a consistent evidence and quality review checklist.','Planned code or content change','Provenance, coverage and validation checks','Preserve sources; distinguish mocks from real execution.','A Skill is a repeatable instruction set for the coding agent. This project’s review skill checks source-linked outputs and honest validation claims.'),
 step('mcp','Read external project state','GitHub MCP integration','Let the coding agent inspect the repository through a connected tool.','Repository/branch request','Published commit and branch information','Use an authorized connected account and verify the reported commit.','MCP means Model Context Protocol. The agent requests an external tool operation, the integration reads GitHub, and structured results return to the agent. This project used MCP to verify main; Git CLI performs commits and pushes.'),
 step('implement','Build and review','React + coding agent + local tools','Implement the agreed application behavior.','Requirements + repository code','Components, readers and documentation','Review changes for accurate tool/status labels and source handling.','PDF.js, SheetJS, Tesseract and other readers are application libraries. They run directly in the app; they are not MCP integrations.'),
 step('verify','Test the result','Node tests + Playwright + fixture evaluation','Check behavior using reproducible inputs and actual browser runs.','Original fixtures and expected source evidence','Pass/fail results and observed issues','Small fixture accuracy does not establish textbook-wide quality.','Unit tests cover logic; Playwright covers desktop/mobile behavior. Real OCR smoke tests are recorded separately from mocked inference tests.'),
 step('deploy','Publish and verify','Git CLI + Vercel CLI','Make the reviewed release available outside the laptop.','Committed repository + production build','Public Vercel site and deployment evidence','Verify the public site and keep secrets server-side.','Vercel hosts the frontend and optional protected AI endpoint. CLI deployment is a separate development action, not an MCP step in student question answering.') ]}
 };
}
