import {test,expect} from '@playwright/test';
import {zipSync,strToU8} from 'fflate';
import * as XLSX from 'xlsx';
const docx=zipSync({'word/document.xml':strToU8('<w:document xmlns:w="urn:word"><w:body><w:p><w:r><w:t>Electric charge is a property of matter.</w:t></w:r></w:p><w:p><w:r><w:t>Like charges repel. Unlike charges attract.</w:t></w:r></w:p></w:body></w:document>')});
const pptx=zipSync({'ppt/presentation.xml':strToU8('<p:presentation xmlns:p="urn:ppt" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><p:sldIdLst><p:sldId r:id="second"/><p:sldId r:id="first"/></p:sldIdLst></p:presentation>'),'ppt/_rels/presentation.xml.rels':strToU8('<Relationships><Relationship Id="second" Target="slides/slide2.xml"/><Relationship Id="first" Target="slides/slide1.xml"/></Relationships>'),'ppt/slides/slide1.xml':strToU8('<a:slide xmlns:a="urn:ppt"><a:p><a:r><a:t>Electric field is force per unit charge.</a:t></a:r></a:p></a:slide>'),'ppt/slides/slide2.xml':strToU8('<a:slide xmlns:a="urn:ppt"><a:p><a:r><a:t>Like charges repel. Unlike charges attract.</a:t></a:r></a:p></a:slide>')});
function book(type){const b=XLSX.utils.book_new();XLSX.utils.book_append_sheet(b,XLSX.utils.aoa_to_sheet([['Concept','Definition'],['Charge','Like charges repel. Unlike charges attract.']]),'Physics');return XLSX.write(b,{type:'buffer',bookType:type});}
function record(type,data,container=false){const b=Buffer.alloc(8);b.writeUInt16LE(container?15:0);b.writeUInt16LE(type,2);b.writeUInt32LE(data.length,4);return Buffer.concat([b,data]);}
const cfb=XLSX.CFB.utils.cfb_new();XLSX.CFB.utils.cfb_add(cfb,'PowerPoint Document',record(1006,record(4000,Buffer.from('Like charges repel. Unlike charges attract.','utf16le')),true));const ppt=XLSX.CFB.write(cfb,{type:'buffer'});
for(const [ext,buffer,label,text] of [['docx',docx,'Word document (paragraph order)','Like charges repel.'],['pptx',pptx,'Slide 1','Like charges repel.'],['ppt',ppt,'Slide 1 (legacy storage order)','Like charges repel.'],['xls',book('biff8'),'Sheet: Physics','Like charges repel.'],['xlsx',book('xlsx'),'Sheet: Physics','Like charges repel.'],['xml',Buffer.from('<lesson><concept>Like charges repel.</concept></lesson>'),'XML document','Like charges repel.'],['txt',Buffer.from('Like charges repel. Unlike charges attract.'),'TXT document','Like charges repel.'],['csv',Buffer.from('Concept,Definition\nCharge,Like charges repel.'),'Sheet: Sheet1','Like charges repel.']])test(`${ext} text is indexed with format-specific source references`,async({page})=>{await page.goto('/');await page.getByLabel('Upload study file').setInputFiles({name:`study.${ext}`,mimeType:'application/octet-stream',buffer:Buffer.from(buffer)});await expect(page.locator('.document-strip')).toContainText(`study.${ext}`);await page.getByRole('region',{name:'Document reading summary'}).getByText('Check source coverage').click();await page.getByRole('button',{name:label,exact:true}).click();await expect(page.getByRole('dialog',{name:'Source evidence'})).toContainText(text);await expect(page.locator('.source-meta')).toContainText(label);await expect(page.getByRole('link',{name:'Download original file'})).toBeVisible();await expect(page.locator('.source-modal iframe')).toHaveCount(0);await page.keyboard.press('Escape');await page.getByRole('button',{name:'Create Short notes',exact:true}).click();await expect(page.locator('.notebook-notes')).toContainText(text);if(ext==='pptx'){await expect(page.locator('.notebook-notes .notebook-page').first()).toContainText('Like charges repel.');}expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
test('XML entities and legacy DOC are rejected without replacing previous document',async({page})=>{await page.goto('/');for(const [name,text,error] of [['unsafe.xml','<!DOCTYPE a [<!ENTITY x "private">]><a>&x;</a>','entities are not supported'],['legacy.doc','legacy','Save it as DOCX or PDF']]){await page.getByLabel('Upload study file').setInputFiles({name,mimeType:'application/octet-stream',buffer:Buffer.from(text)});await expect(page.getByRole('alert')).toContainText(error);await expect(page.locator('.document-strip')).toContainText('Electric charges & fields');}});
test('PNG image OCR keeps original image and source reference',async({page})=>{await page.route('**/src/lib/ocr.js*',r=>r.fulfill({contentType:'application/javascript',body:'export function createOcrSession(){return {recognize:async()=>({text:"Like charges repel. Unlike charges attract.",confidence:95}),close(){}}}'}));await page.goto('/');const data=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=600;c.height=200;const x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,600,200);x.fillStyle='black';x.font='28px Arial';x.fillText('Like charges repel.',20,80);return c.toDataURL().split(',')[1];});await page.getByLabel('Upload study file').setInputFiles({name:'study.png',mimeType:'image/png',buffer:Buffer.from(data,'base64')});await expect(page.locator('.document-strip')).toContainText('study.png');await page.getByRole('button',{name:'Create Short notes',exact:true}).click();await page.locator('.notebook-notes').getByRole('button',{name:'Image 1 S1',exact:true}).first().click();await expect(page.locator('.source-image')).toBeVisible();await expect(page.getByRole('dialog',{name:'Source evidence'})).toContainText('OCR transcription');});
