import {test,expect} from '@playwright/test';
test('flashcards reveal actual diagrams and any individual card downloads SVG',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Create Flash cards',exact:true}).click();await expect(page.getByRole('region',{name:'Visual flashcards'})).toBeVisible();await expect(page.locator('.flashcard-diagram')).toHaveCount(0);
 await page.getByRole('button',{name:'Reveal answer',exact:true}).nth(1).click();await expect(page.locator('.flashcard-diagram')).toHaveCount(1);
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download flashcard 2 SVG'}).click();expect((await download).suggestedFilename()).toBe('flashcard-2.svg');await page.getByRole('button',{name:'Reveal all answers'}).click();await expect(page.locator('.flashcard-diagram')).toHaveCount(4);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
test('demo quizzes are all MCQ, score selected answers and link to evidence',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Create Quiz',exact:true}).click();await expect(page.locator('.mcq-options input')).toHaveCount(16);await expect(page.getByText(/Suggested answer:/)).toHaveCount(0);await page.getByLabel('Repel',{exact:true}).check();await page.getByRole('button',{name:'Check answers'}).click();await expect(page.locator('.quiz-score')).toContainText('Score: 1 / 4');await expect(page.getByText('Suggested answer: Repel',{exact:true})).toBeVisible();await page.getByRole('button',{name:'p. 1 S1',exact:true}).first().click();await expect(page.getByRole('dialog',{name:'Source evidence'})).toBeVisible();
});
test('Hindi local content and Hindi query retrieval use the local worker',async({page})=>{
 await page.addInitScript(()=>{const RealWorker=window.Worker;window.translationRequests=[];window.Worker=class{constructor(url,options){if(!String(url).includes('translation.worker'))return new RealWorker(url,options);}postMessage(data){if(data.type==='clear')return;window.translationRequests.push(data);setTimeout(()=>this.onmessage?.({data:{id:data.id,type:'result',text:data.source==='Hindi'?'electric charge conservation':`हिन्दी: ${data.text}`}}),5);}terminate(){}};});
 let calls=0;await page.route('**/api/study',r=>{calls++;return r.abort();});await page.goto('/');await page.getByLabel('Preferred language',{exact:true}).selectOption('Hindi');await page.getByRole('button',{name:'Create Short notes',exact:true}).click();await expect(page.locator('.notebook-notes')).toHaveAttribute('lang','hi');await expect(page.locator('.notebook-notes')).toContainText('हिन्दी');await page.getByRole('button',{name:'Ask this document',exact:true}).click();await page.getByLabel('Question',{exact:true}).fill('विद्युत आवेश क्या है?');await page.getByRole('button',{name:'Find an answer'}).click();await expect(page.getByRole('heading',{name:'Locally translated source answer'})).toBeVisible();expect(calls).toBe(0);expect(await page.evaluate(()=>window.translationRequests.some(r=>r.source==='Hindi'&&r.target==='English'))).toBe(true);
});
