import {test,expect} from '@playwright/test';
async function stubOcr(page,{failure=false,stall=false}={}){
 await page.addInitScript(()=>{window.ocrRequests=[];window.ocrClosed=0;});
 await page.route('**/src/lib/ocr.js*',r=>r.fulfill({contentType:'text/javascript',body:`export function createOcrSession({language,signal,onProgress}){return {recognize(canvas,page){window.ocrRequests.push({language,page,width:canvas.width,height:canvas.height});onProgress('OCR page '+page+': recognizing text');${failure?"return Promise.reject(new Error('OCR download unavailable'));":stall?"return new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(new DOMException('Cancelled','AbortError')),{once:true}));":"return Promise.resolve({text:'Electric charge is a property of matter. Like charges repel. Unlike charges attract.',confidence:94});"}},close(){window.ocrClosed++;}};}`}));
}
test('OCR image-only page joins the RAG index while blank and selectable pages retain original numbers',async({page})=>{
 await stubOcr(page);await page.goto('/');await page.getByLabel('PDF printed language',{exact:true}).selectOption('Hindi');await page.getByLabel('Upload PDF file').setInputFiles('tests/fixtures/scanned-study-english.pdf');await expect(page.locator('.document-strip')).toContainText('scanned-study-english.pdf');const summary=page.getByRole('region',{name:'Document reading summary'});await expect(summary).toContainText('1 scanned page read with OCR');await expect(summary).toContainText('Page 2 is blank.');expect(await page.evaluate(()=>window.ocrRequests.map(r=>[r.language,r.page]))).toEqual([['Hindi',1]]);expect(await page.evaluate(()=>window.ocrClosed)).toBeGreaterThan(0);
 await page.getByRole('button',{name:'Create Short notes',exact:true}).click();await expect(page.locator('.notebook-notes')).toContainText('Like charges repel.');await page.getByRole('button',{name:'p. 1 S1',exact:true}).first().click();await expect(page.getByRole('dialog',{name:'Source evidence'})).toContainText('OCR transcription');await page.keyboard.press('Escape');await page.getByRole('button',{name:'Ask this PDF',exact:true}).click();await page.getByLabel('Question',{exact:true}).fill('like charges repel');await page.getByRole('button',{name:'Find an answer'}).click();await expect(page.getByRole('heading',{name:'Source-based answer',level:2,exact:true})).toBeVisible();await page.getByRole('tab',{name:'Behind the RAG'}).click();await expect(page.locator('.pipeline-card').filter({has:page.getByRole('heading',{name:'3. OCR',exact:true})})).toContainText('1/1 pages read');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('failed OCR preserves other readable pages and explains omitted coverage',async({page})=>{
 await stubOcr(page,{failure:true});await page.goto('/');await page.getByLabel('Upload PDF file').setInputFiles('tests/fixtures/scanned-study-english.pdf');await expect(page.locator('.document-strip')).toContainText('scanned-study-english.pdf');await expect(page.getByRole('alert')).toContainText('OCR could not finish');await expect(page.getByRole('region',{name:'Document reading summary'})).toContainText('1 page needs manual review');await page.getByRole('button',{name:'Create Short notes',exact:true}).click();await expect(page.locator('.notebook-notes')).toContainText('Electric field');await expect(page.getByRole('button',{name:'p. 3 S1',exact:true}).first()).toBeVisible();
});
test('OCR upload can be cancelled without replacing the previous document',async({page})=>{
 await stubOcr(page,{stall:true});await page.goto('/');await page.getByLabel('Upload PDF file').setInputFiles('tests/fixtures/scanned-study-english.pdf');await expect(page.getByRole('status')).toContainText('recognizing text');await page.getByRole('button',{name:'Cancel PDF processing'}).click();await expect(page.getByRole('status')).toHaveCount(0);await expect(page.getByRole('alert')).toContainText('cancelled');await expect(page.locator('.document-strip')).toContainText('Electric charges & fields');await expect(page.getByRole('button',{name:'Choose PDF',exact:true})).toBeEnabled();
});

test('real OCR initialization cancellation terminates the worker during a stalled download',async({page})=>{
 let held;await page.context().route('https://cdn.jsdelivr.net/npm/tesseract.js-core@7.0.0/**',r=>{held=r;});await page.goto('/');await page.getByLabel('Upload PDF file').setInputFiles('tests/fixtures/scanned-study-english.pdf');await expect.poll(()=>Boolean(held),{timeout:15000}).toBe(true);await page.getByRole('button',{name:'Cancel PDF processing'}).click();await expect(page.getByRole('status')).toHaveCount(0);await expect(page.getByRole('alert')).toContainText('cancelled');await expect.poll(()=>page.workers().length).toBe(0);await held.abort().catch(()=>{});await expect(page.locator('.document-strip')).toContainText('Electric charges & fields');
});
test('real OCR download failure closes its worker and retains selectable pages',async({page})=>{
 await page.context().route('https://cdn.jsdelivr.net/npm/tesseract.js-core@7.0.0/**',r=>r.abort());await page.goto('/');await page.getByLabel('Upload PDF file').setInputFiles('tests/fixtures/scanned-study-english.pdf');await expect(page.locator('.document-strip')).toContainText('scanned-study-english.pdf');await expect(page.getByRole('alert')).toContainText('OCR could not finish');await expect.poll(()=>page.workers().length).toBe(0);await expect(page.getByRole('region',{name:'Document reading summary'})).toContainText('1 of 3 pages have selectable text');
});
