import {test,expect} from '@playwright/test';import {PDFDocument,rgb} from 'pdf-lib';
test('blank page is skipped, short text retained, and only visible no-text page needs review',async({page})=>{
 const pdf=await PDFDocument.create();const first=pdf.addPage([400,500]);first.drawText('Electric charge is a property of matter.',{x:25,y:450,size:12});
 const blank=pdf.addPage([400,500]);blank.drawRectangle({x:0,y:0,width:400,height:500,color:rgb(1,1,1)});
 pdf.addPage([400,500]).drawText('Units',{x:25,y:450,size:12});pdf.addPage([400,500]).drawRectangle({x:25,y:300,width:200,height:80,color:rgb(0,0,0)});
 await page.goto('/');await page.getByLabel('Upload PDF file').setInputFiles({name:'page-coverage.pdf',mimeType:'application/pdf',buffer:Buffer.from(await pdf.save())});
 const summary=page.getByRole('region',{name:'Document reading summary'});await expect(summary).toContainText('Page 2 is blank.');await expect(summary).toContainText('2 of 4 pages have selectable text');
 await expect(page.getByRole('alert')).toContainText('Page 4: Visible content');await expect(page.getByRole('alert')).not.toContainText('Page 2');
 await summary.getByText('Check page coverage and what to do next').click();await expect(summary).toContainText('Short text — included');await summary.getByRole('button',{name:'Page 2',exact:true}).click();await expect(page.getByRole('dialog',{name:'Source evidence'})).toContainText('PDF page 2');await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Create Short notes',exact:true}).click();await expect(page.getByRole('button',{name:'p. 3 S2',exact:true}).first()).toBeVisible();
});
test('graph opens fitted with professional fonts and only selected topic essentials',async({page})=>{
 await page.goto('/');await page.getByRole('button',{name:'Create Mind map',exact:true}).click();await expect(page.locator('.graph-actions')).toContainText('Fit page');
 await expect(page.getByRole('region',{name:'Selected topic essentials'})).toContainText('Select a topic');await expect(page.locator('.reader-topic')).toHaveCount(0);await page.locator('.map-node').first().click();await expect(page.getByRole('region',{name:'Selected topic essentials'})).toContainText('Electric charge');await expect(page.locator('.reader-topic')).toHaveCount(1);await expect(page.getByRole('region',{name:'Selected topic essentials'})).not.toContainText('Electric potential');const font=await page.locator('.hand-node h3').first().evaluate(el=>getComputedStyle(el).fontFamily);expect(font).not.toContain('Caveat');
 const fits=await page.locator('.graph-scroll').evaluate(el=>({width:el.querySelector('svg').getBoundingClientRect().width<=el.clientWidth+1,noVerticalScroll:el.scrollHeight<=el.clientHeight+2}));expect(fits).toEqual({width:true,noVerticalScroll:true});
 await page.getByRole('button',{name:'Zoom in'}).click();await page.getByRole('button',{name:'Study roadmap',exact:true}).click();await page.getByRole('button',{name:'Create material',exact:true}).click();await expect(page.locator('.graph-actions')).toContainText('Fit page');await page.getByLabel('Topic essentials',{exact:true}).selectOption('0');await expect(page.getByRole('region',{name:'Selected topic essentials'})).toContainText('Self-check');await expect(page.locator('.reader-topic')).toHaveCount(1);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});

test('uploaded PDF graphs show only necessary selected content and keep citation navigation',async({page})=>{
 await page.goto('/');await page.getByLabel('Upload PDF file').setInputFiles('tests/fixtures/study.pdf');await expect(page.locator('.document-strip')).toContainText('study.pdf');await page.getByRole('button',{name:'Create Mind map',exact:true}).click();await expect(page.locator('.map-node')).toHaveCount(2);await expect(page.locator('.reader-topic')).toHaveCount(0);await page.getByLabel('Topic essentials',{exact:true}).selectOption('0');await expect(page.locator('.reader-topic')).toHaveCount(1);await expect(page.locator('.reader-topic')).toContainText('Like charges repel.');await expect(page.locator('.reader-topic')).not.toContainText('N/C');expect(await page.locator('.reader-topic li').count()).toBeLessThanOrEqual(3);await page.locator('.reader-topic').getByRole('button',{name:'p. 1 S1',exact:true}).click();await expect(page.getByRole('dialog',{name:'Source evidence'})).toContainText('charge');await page.keyboard.press('Escape');await page.getByLabel('Topic essentials',{exact:true}).selectOption('1');await expect(page.locator('.reader-topic')).toHaveCount(1);await expect(page.locator('.reader-topic')).toContainText('N/C');await expect(page.locator('.reader-topic')).not.toContainText('Like charges repel.');const clipped=await page.locator('.hand-leaf').evaluateAll(els=>els.some(el=>el.scrollHeight>el.clientHeight+1));expect(clipped).toBe(false);
});
