import React,{useState} from 'react';
import {Download,Printer,Workflow} from 'lucide-react';
import {designs,buildArchitectureSvg} from '../lib/architecture.js';
export default function ArchitectureView(){
  const [kind,setKind]=useState('HLD');const [selected,setSelected]=useState(null);const diagram=designs[kind];
  function select(event){const id=event.target.closest('[data-node-id]')?.getAttribute('data-node-id');if(id)setSelected(diagram.nodes.find(n=>n.id===id));}
  function download(){const url=URL.createObjectURL(new Blob([buildArchitectureSvg(kind)],{type:'image/svg+xml'}));const a=document.createElement('a');a.href=url;a.download=`${kind}-architecture.svg`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <section className="architecture-view" aria-label="Visual HLD and LLD"><div className="architecture-toolbar"><div><Workflow size={23}/><h2>Architecture, visually explained</h2><p>Explore the actual system. Select a component to inspect its responsibility.</p></div><div className="architecture-actions"><button aria-pressed={kind==='HLD'} onClick={()=>{setKind('HLD');setSelected(null);}}>HLD</button><button aria-pressed={kind==='LLD'} onClick={()=>{setKind('LLD');setSelected(null);}}>LLD</button><button onClick={download}><Download size={15}/> SVG</button><button onClick={()=>window.print()}><Printer size={15}/> Print / PDF</button></div></div><div className="architecture-caption"><strong>{diagram.title}</strong><span>{diagram.subtitle}</span></div><div className="architecture-canvas" tabIndex={0} onClick={select} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(e);}}} dangerouslySetInnerHTML={{__html:buildArchitectureSvg(kind)}}/>{selected&&<aside className="architecture-detail"><h3>{selected.title}</h3><p>{selected.detail}</p></aside>}<div className="architecture-links"><a href="/docs/HLD.html" target="_blank" rel="noreferrer">Open standalone HLD</a><a href="/docs/LLD.html" target="_blank" rel="noreferrer">Open standalone LLD</a><a href="/docs/RUNBOOK.md" target="_blank" rel="noreferrer">Setup runbook</a><a href="/docs/TOOLS.md" target="_blank" rel="noreferrer">Tools / MCP / Skills</a></div></section>;
}
