import React,{useId} from 'react';
import {BookOpen,Download,RotateCcw,Printer} from 'lucide-react';
function lines(text,max=32){const words=text.split(/\s+/);const out=[];let line='';for(const word of words){if(line&&line.length+word.length+1>max){out.push(line);line=word;}else line+=(line?' ':'')+word;}if(line)out.push(line);return out;}
function Diagram({item,index}){
 const id=useId().replaceAll(':','');const evidence=(item.visual?.points||item.keyPoints||[{text:item.body,sources:item.sources}]).slice(0,3);const labels=evidence.map(p=>lines(p.text));const rootLines=lines(item.visual?.title||item.definition?.text||item.title,53);const rootHeight=Math.max(115,rootLines.length*20+65);const leafY=25+rootHeight+47;const rowHeight=Math.max(130,...labels.map(l=>l.length*22+45));const height=leafY+rowHeight+(item.formula?105:0)+45;
 return <svg id={`card-${index}-${id}`} className="flashcard-diagram" viewBox={`0 0 900 ${height}`} role="img" aria-label={`Source-linked concept diagram: ${item.title}`}><defs><marker id={`card-arrow-${id}`} markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 L8 4 L0 8" fill="#8eabc0"/></marker></defs><rect width="900" height={height} rx="20" fill="#fffdf5"/><rect x="140" y="25" width="620" height={rootHeight} rx="25" fill="#e6f1fa" stroke="#8eb5d1"/><text x="450" y="54" textAnchor="middle" fontSize="15" fill="#65839c">KEY IDEA · CHECK THE SOURCE</text>{rootLines.map((line,j)=><text key={j} x="450" y={80+j*20} textAnchor="middle" fontSize="17" fill="#244e6c">{line}</text>)}{evidence.map((p,j)=>{const w=840/evidence.length;const x=30+j*w;const center=x+w/2;return <g key={j}><path d={`M450 ${rootHeight+25} C450 ${rootHeight+52} ${center} ${leafY-25} ${center} ${leafY-2}`} fill="none" stroke="#8eabc0" strokeWidth="2" markerEnd={`url(#card-arrow-${id})`}/><rect x={x+5} y={leafY} width={w-10} height={rowHeight} rx="15" fill={['#edf5dd','#fff0ca','#fae5e7'][j]} stroke="#d7decc"/>{labels[j].map((line,k)=><text key={k} x={center} y={leafY+31+k*22} textAnchor="middle" fontSize="16" fill="#35565f">{line}</text>)}</g>;})}{item.formula&&<><rect x="30" y={leafY+18+rowHeight} width="840" height="83" rx="12" fill="#f6eacb"/>{lines(item.formula.text,80).map((line,j)=><text key={j} x="450" y={leafY+45+rowHeight+j*21} textAnchor="middle" fontSize="17" fill="#685737">{line}</text>)}</>}<text x="35" y={height-14} fontSize="13" fill="#536e7f">Supporting passages: {item.sources.join(', ')} · Study Atlas</text></svg>;
}
export default function Flashcards({items,chunks,language,revealed,onReveal,onSource}){
 function download(index){const svg=document.querySelectorAll('.visual-study-card')[index]?.querySelector('.flashcard-diagram');if(!svg)return;const clone=svg.cloneNode(true);clone.setAttribute('xmlns','http://www.w3.org/2000/svg');clone.setAttribute('font-family','Arial, sans-serif');const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(clone)],{type:'image/svg+xml'}));const a=document.createElement('a');a.href=url;a.download=`flashcard-${index+1}.svg`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="visual-flashcards" lang={{English:'en',Tamil:'ta',Hindi:'hi'}[language]||'en'} aria-label="Visual flashcards"><header><div><h3>Picture the idea. Recall the answer.</h3><p>Reveal a source-linked concept diagram, then explain the idea without looking. Diagrams organize evidence; they do not interpret PDF images.</p></div><button className="secondary" onClick={()=>items.forEach((_,i)=>{if(!revealed[i])onReveal(i);})}>Reveal all answers</button><button className="secondary" onClick={()=>window.print()}><Printer size={16}/> Print cards</button></header><div className="visual-card-grid">{items.map((item,i)=><article className={`visual-study-card ${revealed[i]?'is-revealed':''}`} key={i}><div className="flashcard-number">CARD {String(i+1).padStart(2,'0')} · {revealed[i]?'ANSWER':'RECALL'}</div><h4>{item.title}</h4>{!revealed[i]&&<div className="recall-illustration" aria-hidden="true"><BookOpen size={55}/><span>?</span><p>Pause. Think. Explain.</p></div>}<button className="secondary reveal" onClick={()=>onReveal(i)}><RotateCcw size={16}/>{revealed[i]?'Hide answer':'Reveal answer'}</button>{revealed[i]&&<><Diagram item={item} index={i}/><p className="visual-card-answer">{item.body}</p>{item.original&&<details className="original-comparison"><summary>Compare original wording</summary><p>{item.original.title}</p><p>{item.original.body}</p></details>}<div className="source-links">{item.sources.map(id=>{const c=chunks.find(c=>c.id===id);return c?<button key={id} onClick={()=>onSource(c)}>{c.sourceLabel||`p. ${c.page}`} {id}</button>:null;})}</div><button className="secondary card-download" aria-label={`Download flashcard ${i+1} SVG`} onClick={()=>download(i)}><Download size={15}/> Download card image (SVG)</button></>}</article>)}</div></section>;
}
