import React,{useEffect,useState} from 'react';
import {Play,Pause,RotateCcw,SkipForward,ArrowRight,FileCheck,FileText,ScanText,Tags,Scissors,Brain,Lightbulb,Database,MessagesSquare,Languages,Search,Layers,Sparkles,BookOpen,ClipboardList,ShieldCheck,Plug,Code2,CheckCircle2,CloudUpload,Clock3} from 'lucide-react';
import {buildFlowPaths} from '../lib/flow-model.js';
const icons={validate:FileCheck,decode:FileText,ocr:ScanText,structure:Tags,chunk:Scissors,embed:Brain,index:Database,question:MessagesSquare,translate:Languages,retrieve:Search,context:Layers,compose:Sparkles,cite:BookOpen,requirements:ClipboardList,skill:ShieldCheck,mcp:Plug,implement:Code2,verify:CheckCircle2,deploy:CloudUpload,choose:ClipboardList,coverage:Layers,essential:Lightbulb,material:Sparkles,language:Languages,render:BookOpen};
export default function RagWalkthrough(props){
 const paths=buildFlowPaths(props);const [path,setPath]=useState('upload'),[active,setActive]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(2200),[reduced,setReduced]=useState(false);
 const current=paths[path],selected=current.steps[active]||current.steps[0];
 useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>{setReduced(media.matches);if(media.matches)setPlaying(false);};update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
 useEffect(()=>{if(!playing)return;const timer=setTimeout(()=>{if(active>=current.steps.length-1)setPlaying(false);else setActive(i=>i+1);},speed);return()=>clearTimeout(timer);},[playing,active,speed,current.steps.length]);
 function choose(value){setPath(value);setActive(0);setPlaying(false);}
 function play(){if(active===current.steps.length-1)setActive(0);setPlaying(v=>!v);}
 const example=props.doc?.chunks?.[0];
 return <section className="rag-walkthrough" aria-label="Animated RAG walkthrough" data-playing={playing} data-reduced-motion={reduced}>
 <header className="flow-header"><div><span className="eyebrow">EXPLORE THE SYSTEM</span><h2>See how the pieces work together</h2><p>RAG means Retrieval-Augmented Generation: find document evidence, then use it to build a grounded response. Select a step to inspect its input, output and checks.</p></div><span className="flow-playback-label"><Clock3 size={14}/>Educational playback</span></header>
 <div className="flow-paths" role="group" aria-label="Flow paths">{Object.entries(paths).map(([id,value])=><button key={id} aria-pressed={path===id} onClick={()=>choose(id)}>{id==='upload'?<FileText size={17}/>:id==='question'?<MessagesSquare size={17}/>:id==='materials'?<BookOpen size={17}/>:<Plug size={17}/>} {id==='upload'?'Document preparation':id==='question'?'Question answering':id==='materials'?'Study materials':'MCP & development'}</button>)}</div>
 <div className="flow-controls"><button className="primary" onClick={play}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?'Pause walkthrough':'Play walkthrough'}</button><button className="secondary" onClick={()=>{setPlaying(false);setActive(0);}}><RotateCcw size={15}/>Replay from start</button><button className="secondary" disabled={active===current.steps.length-1} onClick={()=>{setPlaying(false);setActive(i=>Math.min(i+1,current.steps.length-1));}}><SkipForward size={16}/>Next step</button><label>Playback speed<select aria-label="Walkthrough playback speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={3500}>Slow</option><option value={2200}>Normal</option><option value={1100}>Fast</option></select></label></div>
 <div className="flow-path-intro"><h3>{current.title}</h3><p>{current.summary}</p><small>Playback speed illustrates the sequence. Actual processing times remain in the measured stage cards below.{reduced?' Reduced motion is enabled; moving effects are disabled.':''}</small></div>
 <p className="flow-step-announcement" role="status" aria-live="polite">Step {active+1} of {current.steps.length}: {selected.title}</p>
 <ol className="flow-nodes" style={{'--flow-count':current.steps.length}} aria-label={`${current.title} steps`}>{current.steps.map((s,i)=>{const Icon=icons[s.id]||Layers;return <li className={`flow-node ${i===active?'flow-active':i<active?'flow-passed':''}`} key={s.id}><button onClick={()=>{setActive(i);setPlaying(false);}} aria-current={i===active?'step':undefined} aria-label={`Inspect step ${i+1}: ${s.title}`}><span className="flow-node-top"><span className="flow-node-icon"><Icon size={21}/></span><span className="flow-node-number">{String(i+1).padStart(2,'0')}</span></span><strong>{s.title}</strong><span className="flow-tool">{s.tool}</span><span className="flow-node-status">{s.optional?'Optional · ':''}{s.status||'Select for details'}</span></button>{i<current.steps.length-1&&<span className="flow-connector" aria-hidden="true"><ArrowRight size={18}/><i/></span>}</li>;})}</ol>
 <div className="flow-progress" role="progressbar" aria-label="Walkthrough progress" aria-valuemin={1} aria-valuemax={current.steps.length} aria-valuenow={active+1}><span style={{width:`${(active+1)/current.steps.length*100}%`}}/></div>
 <article className="flow-detail" aria-label="Selected flow step details"><div className="flow-detail-heading"><div><span className="eyebrow">STEP {active+1} OF {current.steps.length}</span><h3>{selected.title}</h3><p>{selected.purpose}</p></div><span className="flow-detail-tool">{selected.tool}</span></div><dl className="flow-contract"><div><dt>Input</dt><dd>{selected.input}</dd></div><div><dt>Output</dt><dd>{selected.output}</dd></div><div><dt>Validation</dt><dd>{selected.validation}</dd></div></dl><details open><summary>How this step works</summary><p>{selected.detail}</p></details>{selected.metric&&<p className="flow-metric"><Clock3 size={15}/>Current document: {selected.metric}</p>}</article>
 <div className="flow-context"><div><h3>Your current session</h3><p>{props.doc?`${props.doc.name} · ${props.doc.chunks.length} readable passages`:'Upload a supported file to inspect real evidence.'}</p><p>{props.vectors?'Keyword and semantic retrieval enabled.':'Keyword retrieval enabled; semantic search is optional.'} Cloud AI {props.aiConfigured?'configured':'not configured'}.</p></div>{example&&<details><summary>Inspect a real passage from this session</summary><span className="flow-source-label">{example.id} · {example.sourceLabel||`Page ${example.page}`}{example.origin==='ocr'?' · OCR transcription':''}</span><blockquote>{example.text}</blockquote></details>}</div>
 </section>;
}
