import React from 'react';
import {Lightbulb,FlaskConical,TriangleAlert,BookOpen,Target,Printer} from 'lucide-react';
const labels={English:{definition:'Key concept',points:'Must-know points',formula:'Formula & units',example:'Example from the evidence',confusion:'Avoid this confusion',source:'Textbook wording',check:'Check your understanding',goal:'Learning goal'},Tamil:{definition:'முக்கிய கருத்து',points:'அறிய வேண்டியவை',formula:'சூத்திரம் மற்றும் அலகுகள்',example:'ஆதாரத்தில் உள்ள எடுத்துக்காட்டு',confusion:'இந்தக் குழப்பத்தைத் தவிர்',source:'பாடப்புத்தகச் சொற்கள்',check:'புரிதலைச் சரிபார்',goal:'கற்றல் நோக்கம்'}};
export default function StudyNotes({items,language,title,onSource,chunks,feature}){
  labels.Hindi={definition:'मुख्य अवधारणा',points:'ज़रूरी बातें',formula:'सूत्र और इकाइयाँ',example:'स्रोत से उदाहरण',confusion:'इस भ्रम से बचें',source:'पाठ्यपुस्तक के शब्द',check:'अपनी समझ जाँचें',goal:'सीखने का लक्ष्य'};
  const l=labels[language]||labels.English;
  const cite=ids=><div className="source-links">{ids.map(id=>{const c=chunks.find(c=>c.id===id);return c?<button key={id} onClick={()=>onSource(c)}><BookOpen size={12}/> p. {c.page}<span>{id}</span></button>:null;})}</div>;
  const block=(value,label,kind,Icon)=>value&&<section className={`note-callout ${kind}`}><h4>{Icon&&<Icon size={17}/>} {label}</h4><p>{value.text}</p>{cite(value.sources)}</section>;
  return <section className="notebook-notes" lang={{English:'en',Tamil:'ta',Hindi:'hi'}[language]||'en'} aria-label="Structured notebook notes"><header className="notebook-header"><span>STUDY ATLAS · SOURCE-LINKED LEARNING</span><h2>{title}</h2><p>{language==='Tamil'?'புரிந்துகொள். நினைவுகூர். சரிபார்.':'Understand the idea. Remember the essentials. Check the source.'}</p><button className="secondary" onClick={()=>window.print()}><Printer size={15}/> Print / Save PDF</button></header><div className="notebook-pages">{items.map((item,i)=><article className="notebook-page" key={i}><div className="page-topic"><span>{String(i+1).padStart(2,'0')}</span><h3>{item.title}</h3></div><div className="note-columns"><div className="note-main">{block(item.definition,l.definition,'concept',Lightbulb)}{item.keyPoints?.length?<section className="note-points"><h4>{l.points}</h4><ul>{item.keyPoints.map((p,j)=><li key={j}><span>{p.text}</span>{cite(p.sources)}</li>)}</ul></section>:<p className="note-body">{item.body}</p>}{block(item.formula,l.formula,'formula',FlaskConical)}{block(item.example,l.example,'example',Lightbulb)}</div><aside className="note-sidebar">{item.original&&<section className="note-callout original-comparison"><h4>Original wording — compare translation</h4><h5>{item.original.title}</h5><p>{item.original.body}</p>{cite(item.original.sources)}</section>}{block(item.textbookExcerpt,l.source,'excerpt',BookOpen)}{block(item.misconception,l.confusion,'confusion',TriangleAlert)}{block(item.checkpoint,l.check,'checkpoint',Target)}{!item.textbookExcerpt&&!item.checkpoint&&<section className="note-callout checkpoint"><h4>{l.check}</h4><p>{language==='Tamil'?'இந்தக் கருத்தை உங்கள் சொற்களில் விளக்கி ஆதாரத்துடன் ஒப்பிடுங்கள்.':'Explain the concept without looking, then compare your explanation with the cited passage.'}</p>{cite(item.sources)}</section>}</aside></div>{cite(item.sources)}</article>)}</div></section>;
}
