import React,{useId,useMemo,useState,useEffect} from 'react';
import {ZoomIn,ZoomOut,RotateCcw,ChevronLeft,ChevronRight,BookOpen,Check,Printer,Presentation} from 'lucide-react';
const colors=[['#fbe6e6','#ba7373'],['#e2f1fb','#659cc0'],['#edf6d6','#8ea456'],['#fdf1d1','#bf9b47'],['#eee5f8','#a087b4'],['#fce8d9','#bd9067']];
const excerpt=(text,length=130)=>text.length>length?`${text.slice(0,length).trim()}…`:text;
function groupTopics(items){const groups=new Map();for(const item of items){const key=item.title.trim().toLowerCase();if(!groups.has(key))groups.set(key,{...item,sources:[...item.sources]});else{const current=groups.get(key);current.body+='\n'+item.body;current.sources=[...new Set([...current.sources,...item.sources])];current.subtopics=[...(current.subtopics||[]),...(item.subtopics||[])];}}return [...groups.values()];}
function cloud(w,h){return `M${w*.1},${h*.3} C${-w*.03},${h*.09} ${w*.18},${-h*.05} ${w*.3},${h*.1} C${w*.43},${-h*.03} ${w*.65},0 ${w*.72},${h*.14} C${w*.94},${h*.05} ${w*1.06},${h*.25} ${w*.95},${h*.47} C${w*1.06},${h*.69} ${w*.92},${h*.94} ${w*.77},${h*.85} C${w*.68},${h*1.06} ${w*.43},${h*1.02} ${w*.36},${h*.89} C${w*.16},${h*1.04} 0,${h*.8} ${w*.1},${h*.64} C${-w*.03},${h*.52} 0,${h*.35} ${w*.1},${h*.3} Z`;}
export default function StudyGraph({items,title,type,chunks,onSource,language='English'}){
 const marker=useId().replaceAll(':','');const [zoom,setZoom]=useState(.85);const [page,setPage]=useState(0);const [selected,setSelected]=useState(null);const [reviewed,setReviewed]=useState(new Set());const [slide,setSlide]=useState(false);
 const topics=useMemo(()=>groupTopics(items),[items]);useEffect(()=>{setPage(0);setSelected(null);setReviewed(new Set());},[items]);
 const tamil=language==='Tamil';const limit=6;const visible=topics.slice(page*limit,(page+1)*limit);const totalPages=Math.ceil(topics.length/limit);const roadmap=type==='roadmap';
 const width=1200;const height=roadmap?visible.length*190+155:Math.max(770,Math.ceil(visible.length/2)*440+105);const nodes=[];const edges=[];
 if(!roadmap){
  const root={id:'root',x:475,y:height/2-90,w:250,h:175,title,body:tamil?'தலைப்பைத் தேர்ந்தெடுத்து அதன் கருத்துகளையும் ஆதாரங்களையும் படிக்கவும்.':'Select a topic to read its ideas and supporting evidence.',sources:[],kind:'root',color:['#fff0b8','#bd9d53']};nodes.push(root);
  visible.forEach((topic,i)=>{
   const x=i%2?810:30;const y=45+Math.floor(i/2)*440;const color=colors[i%colors.length];
   const branch={...topic,id:`topic-${i}`,x,y,w:350,h:65,kind:'topic',color};nodes.push(branch);edges.push({from:root,to:branch});
   const subtopics=topic.subtopics?.length?topic.subtopics:topic.keyPoints?.map(p=>({title:excerpt(p.text,45),points:[p],sources:p.sources}))||[{title:topic.title,points:[{text:topic.body,sources:topic.sources}],sources:topic.sources}];
   subtopics.slice(0,3).forEach((sub,j)=>{const leaf={id:`leaf-${i}-${j}`,x,y:y+82+j*112,w:350,h:110,title:sub.title,body:sub.points.map(p=>p.text).join('\n'),points:sub.points,sources:[...new Set([...sub.sources,...sub.points.flatMap(p=>p.sources)])],original:topic.original?.subtopics?.[j],kind:'leaf',color};nodes.push(leaf);edges.push({from:branch,to:leaf});});
  });
 }else{
  visible.forEach((topic,i)=>{const node={...topic,id:`step-${i}`,x:140,y:95+i*190,w:1000,h:165,kind:'step',color:colors[i%colors.length],number:page*limit+i+1};nodes.push(node);if(i)edges.push({from:nodes[i-1],to:node});});
 }
 function exportSvg(){const svg=document.getElementById(`graph-${marker}`);const clone=svg.cloneNode(true);clone.setAttribute('xmlns','http://www.w3.org/2000/svg');const style=document.createElementNS('http://www.w3.org/2000/svg','style');style.textContent='.hand-node{font-family:Arial,sans-serif;padding:5px 12px;box-sizing:border-box;color:#354951;height:100%;overflow:hidden}.hand-node h3{font-size:16px;margin:3px 0}.hand-node ul{margin:4px 0;padding-left:18px}.hand-node li{font-size:13px;line-height:1.5}.hand-node small{font-size:10px}.hand-root,.hand-topic{text-align:center;display:flex;align-items:center;justify-content:center;flex-direction:column}.hand-root h3{font-size:23px}.hand-topic h3{font-size:20px}.hand-step{display:grid;grid-template-columns:340px 1fr;gap:22px;padding:16px 22px}.hand-step p{font-size:13px;line-height:1.5;margin:6px 0}.hand-step h3{font-size:22px}.hand-step strong{font-size:13px}.graph-node{cursor:pointer}';clone.prepend(style);const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(clone)],{type:'image/svg+xml'}));const a=document.createElement('a');a.href=url;a.download=`study-${type}.svg`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const sourcePages=node=>[...new Set(node.sources.map(id=>chunks.find(c=>c.id===id)?.page).filter(Boolean))].map(p=>`p. ${p}`).join(' · ');
 return <section className={`study-graph illustrated-graph ${roadmap?'roadmap-graph':'mindmap-graph'} ${slide?'slide-view':''}`} lang={tamil?'ta':'en'} aria-label={roadmap?'Graphical study roadmap':'Graphical mind map'}>
  <div className="graph-toolbar"><div><strong>{roadmap?(tamil?'உங்கள் கற்றல் பாதை':'Your illustrated learning roadmap'):(tamil?'ஒரு பார்வையில் முக்கிய கருத்துகள்':'A mind map worth remembering')}</strong><p>{roadmap?'Document-order learning goals and self-checks; prerequisites are not verified.':'Named concepts and short key ideas, with supporting page references.'}</p></div><div className="graph-actions"><button aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(.4,z-.15))}><ZoomOut size={17}/></button><span>{Math.round(zoom*100)}%</span><button aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(1.8,z+.15))}><ZoomIn size={17}/></button><button aria-label="Reset graph zoom" onClick={()=>setZoom(.85)}><RotateCcw size={15}/></button><button className="svg-export" onClick={exportSvg}>Export SVG</button><button aria-label="Toggle slide view" onClick={()=>setSlide(s=>!s)}><Presentation size={16}/></button><button aria-label="Print study slides" onClick={()=>window.print()}><Printer size={16}/></button></div></div>
  <div className="graph-scroll" tabIndex={0} aria-label="Scrollable graph canvas"><svg id={`graph-${marker}`} viewBox={`0 0 ${width} ${height}`} style={{width:width*zoom,height:height*zoom}} role="group" aria-label={roadmap?'Connected roadmap steps':'Connected topic hierarchy'}>
   <defs><pattern id={`lines-${marker}`} width="1200" height="32" patternUnits="userSpaceOnUse"><path d="M0 31.5 H1200" stroke="#d6e7f0" strokeWidth="1"/></pattern><marker id={`arrow-${marker}`} markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8" fill="#a3a69b"/></marker></defs>
   <rect width={width} height={height} fill="#fffef8"/>{roadmap&&<><rect width={width} height={height} fill={`url(#lines-${marker})`}/><path d={`M110 0 V${height}`} stroke="#eabfbb" strokeWidth="1.5"/><text x="140" y="48" className="roadmap-sheet-title">{tamil?'புரிதலிலிருந்து பயிற்சி வரை':'Understand → Recall → Practise → Revise'}</text></>}
   {edges.map(({from,to},i)=>{let path;if(roadmap)path=`M100 ${from.y+from.h/2+30} C70 ${from.y+from.h/2+80} 70 ${to.y+to.h/2-80} 100 ${to.y+to.h/2-30}`;else if(from.kind==='root'){const left=to.x<from.x;const x1=left?from.x:from.x+from.w;const x2=left?to.x+to.w:to.x;path=`M${x1} ${from.y+from.h/2} C${left?x1-60:x1+60} ${from.y+from.h/2} ${left?x2+60:x2-60} ${to.y+to.h/2} ${x2} ${to.y+to.h/2}`;}else path=`M${from.x+5} ${from.y+from.h} V${to.y+24} H${to.x+16}`;return <path key={i} className="graph-edge" d={path} fill="none" stroke={to.color?.[1]||'#a2ab99'} strokeWidth={from.kind==='root'?2.5:1.3} opacity={from.kind==='root'?1:.5} markerEnd={`url(#arrow-${marker})`}/>;})}
   {nodes.map(node=><g key={node.id} className={`graph-node ${node.kind==='root'?'map-root graph-root':node.kind==='topic'?'map-node':node.kind==='step'?'roadmap-node':'idea-node'} ${selected?.id===node.id?'graph-selected':''}`} transform={`translate(${node.x},${node.y})`} role="button" tabIndex={0} aria-label={`Explore ${node.title}`} onClick={()=>setSelected(node)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(node);}}}>
    {['root','topic'].includes(node.kind)?<><path d={cloud(node.w,node.h)} fill={node.color[0]} stroke={node.color[1]} strokeWidth="2"/><path d={cloud(node.w*.985,node.h*.98)} fill="none" stroke={node.color[1]} strokeWidth=".7" opacity=".5" transform="translate(3,2)"/></>:<rect width={node.w} height={node.h} rx={node.kind==='step'?15:4} fill={node.kind==='step'?(reviewed.has(node.title)?'#e8f3dc':node.color[0]):'transparent'} stroke={selected?.id===node.id?node.color[1]:'transparent'} strokeWidth="1.5"/>}
    {node.kind==='step'&&<><circle cx="-42" cy={node.h/2} r="29" fill={node.color[0]} stroke={node.color[1]} strokeWidth="2"/><text x="-42" y={node.h/2+9} textAnchor="middle" fontSize="25" fontWeight="600" fill={node.color[1]}>{node.number}</text></>}
    <foreignObject x="0" y="0" width={node.w} height={node.h}><div xmlns="http://www.w3.org/1999/xhtml" className={`hand-node hand-${node.kind}`}>
     {node.kind==='root'?<><span>✦ {tamil?'கருத்து வரைபடம்':'MIND MAP'}</span><h3>{excerpt(node.title,90)}</h3></>:node.kind==='topic'?<h3>{excerpt(node.title,70)}</h3>:node.kind==='leaf'?<><h3 style={{color:node.color[1]}}>{node.title}</h3><ul>{node.points.slice(0,2).map((p,j)=><li key={j}>{excerpt(p.text,90)}</li>)}</ul></>:<><div><h3>{node.title}</h3><p>{excerpt(node.learningGoal||node.body,145)}</p><small>{sourcePages(node)}{reviewed.has(node.title)?' · REVIEWED':''}</small></div><div><ul>{(node.keyPoints||[]).slice(0,3).map((p,j)=><li key={j}>{excerpt(p.text,105)}</li>)}</ul>{node.checkpoint&&<p className="roadmap-check"><strong>{tamil?'சுய சோதனை':'Self-check'}:</strong> {excerpt(node.checkpoint.text,110)}</p>}</div></>}
    </div></foreignObject>
   </g>)}
   <text x="50" y={height-18} fontSize="12" fill="#a3a69b">Study Atlas · Source-linked study material · Select a node to check the evidence</text>
  </svg></div>
  <div className="graph-pagination"><span>{topics.length} topics · Select a node for full content and sources</span>{totalPages>1&&<div><button aria-label="Previous graph topics" disabled={page===0} onClick={()=>{setPage(p=>p-1);setSelected(null);}}><ChevronLeft size={16}/></button><span>Page {page+1} of {totalPages}</span><button aria-label="Next graph topics" disabled={page===totalPages-1} onClick={()=>{setPage(p=>p+1);setSelected(null);}}><ChevronRight size={16}/></button></div>}</div>
  {selected&&<aside className="graph-inspector"><div className="eyebrow">{tamil?'தேர்ந்தெடுத்த கருத்து':'SELECTED LEARNING IDEA'}</div><h3>{selected.title}</h3><p>{selected.learningGoal?selected.learningGoal+'\n':''}{selected.body}</p>{selected.original&&<section className="original-comparison"><strong>Original wording — compare translation</strong><h4>{selected.original.title}</h4><p>{selected.original.body||selected.original.points?.map(p=>p.text).join('\n')}</p></section>}{selected.checkpoint&&<p><strong>Self-check: </strong>{selected.checkpoint.text}</p>}<div className="source-links">{selected.sources.map(id=>{const c=chunks.find(c=>c.id===id);return c?<button key={id} onClick={()=>onSource(c)}><BookOpen size={12}/> p. {c.page}<span>{id}</span></button>:null;})}</div>{roadmap&&<button className="secondary" onClick={()=>setReviewed(previous=>{const next=new Set(previous);next.has(selected.title)?next.delete(selected.title):next.add(selected.title);return next;})}><Check size={14}/>{reviewed.has(selected.title)?'Mark as not reviewed':'Mark as reviewed'}</button>}</aside>}
 </section>;
}
