import React from 'react';
import {Check} from 'lucide-react';
export default function TopicReader({item,chunks,onSource,roadmap,reviewed,onReview}){
 if(!item)return <section className="topic-reader topic-reader-empty" aria-label="Selected topic essentials"><h3>Select a topic for a focused explanation</h3><p>Choose a diagram node or use the topic selector. You will see only its key ideas and supporting PDF pages.</p></section>;
 const points=(item.points||item.keyPoints||[]).slice(0,3);
 const main=item.definition?.text||(!points.length?item.body:null);
 const sourceIds=[...new Set([...(item.sources||[]),...points.flatMap(p=>p.sources)])];
 return <section className="topic-reader graph-inspector" aria-label="Selected topic essentials"><header><span className="eyebrow">SELECTED TOPIC</span><h3>{item.title}</h3><p>{roadmap?item.learningGoal:'Essential ideas only — check the cited pages for the complete source.'}</p></header><article className="reader-topic">{main&&!points.some(p=>p.text===main)&&<p>{main}</p>}{points.length>0&&<ul>{points.map((point,i)=><li key={i}>{point.text}</li>)}</ul>}{item.formula&&!points.some(p=>p.text===item.formula.text)&&<p className="reader-formula"><strong>Formula: </strong>{item.formula.text}</p>}{roadmap&&item.checkpoint&&<p className="reader-check"><strong>Self-check: </strong>{item.checkpoint.text}</p>}<div className="source-links">{sourceIds.map(id=>{const c=chunks.find(c=>c.id===id);return c?<button key={id} onClick={()=>onSource(c)}>p. {c.page} {id}</button>:null;})}</div>{item.original&&<details><summary>Compare original wording</summary><p>{item.original.definition?.text||item.original.points?.map(p=>p.text).join('\n')||item.original.body}</p></details>}{roadmap&&<button className="secondary" onClick={onReview}><Check size={14}/>{reviewed?'Mark as not reviewed':'Mark as reviewed'}</button>}</article></section>;
}
